config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'top/index' => 'top#index'
  resources :imgposts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :comments, only: [:destroy]
  root 'top#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :imgpost
end

app/models/imgpost.rb
class Imgpost < ApplicationRecord

  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :imgpost
  belongs_to :user

  validates_uniqueness_of :imgpost_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :imgposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_imgposts, through: :likes, source: :imgpost
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  validates :name, presence: true
  validates :profile, length: {maximum: 200}

  mount_uploader :image, ImageUploader

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def already_liked?(imgpost)
    self.likes.exists?(imgpost_id: imgpost.id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    imgpost = Imgpost.find(params[:imgpost_id])
    comment = imgpost.comments.build(comment_params)
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path)
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to imgposts_path
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
    
end

app/controllers/imgposts_controller.rb
class ImgpostsController < ApplicationController

  before_action :authenticate_user!

  def index
    if params[:search] == nil
      @imgposts = Imgpost.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    elsif params[:search] == ''
      @imgposts = Imgpost.includes(:liked_users).sort {|a,b| b.liked_users.size <=> a.liked_users.size}
    else
      @imgposts = Imgpost.where("body LIKE ? ", '%' + params[:search] + '%')
    end
  end

  def new
    @imgpost = Imgpost.new
  end

  def create
    imgpost = Imgpost.new(imgpost_params)
    imgpost.user_id = current_user.id
    if imgpost.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @imgpost = Imgpost.find(params[:id])
    @comments = @imgpost.comments
    @comment = Comment.new
  end

  def edit
    @imgpost = Imgpost.find(params[:id])
    redirect_to imgposts_path unless current_user.id == @imgpost.user_id
  end

  def update
    imgpost = Imgpost.find(params[:id])
    if imgpost.update(imgpost_params)
      redirect_to :action => "show", :id => imgpost.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    imgpost = Imgpost.find(params[:id])
    imgpost.destroy
    redirect_to action: :index
  end

  private
  def imgpost_params
    params.require(:imgpost).permit(:title, :body, :image)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(imgpost_id: params[:imgpost_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(imgpost_id: params[:imgpost_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user , only: [:create, :destroy]

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to @user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to @user
    end
  end

  private

  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/imgposts_helper.rb
module ImgpostsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/imgposts/edit.html.erb
<form class="p-5">
  <h1 class="edit-title">編集ページ</h1>
  <%= form_for @imgpost do |f| %>
  <div class="form-group">
    <label for="exampleInputEmail1"><%= f.label :"タイトル" %></label>
    <%= f.text_field :title, class: "form-control" , placeholder: "タイトルを入力してください" %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1"><%= f.label :"投稿内容" %></label>
    <%= f.text_field :body, class: "form-control" , placeholder: "投稿内容を入力してください" %>
  </div>
  <button type="submit" class="btn btn-primary">編集する</button>
  <% end %>
</form>

app/views/imgposts/index.html.erb
<div class="imgpost-section">

  <%# ヘッダー部分 %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="http://localhost:3000/imgposts"><h1 class="header-title">GeekInstagram</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://localhost:3000/imgposts">ホーム <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", user_path(current_user.id) , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= button_to 'ログアウト', destroy_user_session_path, method: :delete , class: 'nav-link btn btn-light' %>
        </li>
      </ul>
      <%= form_tag({controller: "imgposts", action: "index"}, method: :get , class: 'form-inline my-2 my-lg-0' ) do %>
        <%= text_field_tag :search , nil , class: 'form-control mr-sm-2' %>
        <%= submit_tag '検索する' , class: 'btn btn-outline-success my-2 my-sm-0'  %>
      <% end %>
    </div>
  </nav>

  <br>

  <h3 class="imgpost-title">投稿一覧</h3>

  <p class="text-center"><%= link_to "新規投稿ページへ", new_imgpost_path, class: 'btn btn-primary' %></p>


  <div class="container-fluid">
    <div class="row">
      <% @imgposts.each do |t| %>
        <div class="text-center col-md-6">
          <div class="card mx-auto mb-5" style="width: 18rem;">
            <%# 画像部分 %>
            <%= image_tag t.image_url, class: "card-img-top imgpost-image" if t.image? %>
            <div class="card-body">
              <%# タイトル部分 %>
              <h5 class="card-title"><%= t.title %></h5>

              <%# 投稿内容部分 %>
              <p class="card-text"><%= t.body %></p>

              <%# 投稿者のユーザーページ部分 %>
              <p class="card-text"><a href="/users/<%= t.user_id %>" class="btn btn-link">ユーザーページ</a></p>

              <%# いいね部分 %>
              <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                  <%= link_to imgpost_like_path(id: t.id, imgpost_id: t.id), method: :delete, remote: true do %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
                <% else %>
                  <%= link_to imgpost_likes_path(id: t.id, imgpost_id: t.id), method: :post , remote: true do %>
                  <i class="far fa-heart"></i><%= t.likes.count %>
                  <% end %>
                <% end %>
              <% else %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>

              <br>
              <p class="card-text"><%= link_to "詳細へ", imgpost_path(t.id) , class: "btn btn-link" %></p>
              <p class="card-text"><%= link_to "編集する", edit_imgpost_path(t.id), class: "btn btn-primary" %></p>
              <p class="card-text"><%= button_to "削除する", imgpost_path(t.id), method: :delete , class: "btn btn-info" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/imgposts/new.html.erb
<div class="new-section">
  <h1>GeekInstagram</h1>
  <h3 class="text-primary">新規投稿</h3>
  
  <%# 投稿部分 %>
  <%= form_for @imgpost do |f| %>
    <%# タイトル %>
    <div class="form-group">
      <%= f.label :"タイトル" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <%# 内容 %>
    <div class="form-group">
      <%= f.label :"内容" %>
      <%= f.text_field :body, class: "form-control" %>
    </div>

    <%# 画像 %>
    <div class="form-group">
      <%= f.label :"画像" %>
      <%= f.file_field :image , class: "form-control-file text-center" %>
    </div>

    <%= f.submit "投稿する" , class: 'btn btn-primary' %>
  <% end %>
  <%= link_to "トップへ戻る", imgposts_path %>
</div>
  

app/views/imgposts/show.html.erb
<div class="detail-section">

  <%# ヘッダー部分 %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="http://localhost:3000/imgposts"><h1 class="header-title">GeekInstagram</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://localhost:3000/imgposts">ホーム <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", user_path(current_user.id) , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= button_to 'ログアウト', destroy_user_session_path, method: :delete , class: 'nav-link btn btn-light' %>
        </li>
      </ul>
    </div>
  </nav>

  <%# 詳細部分 %>
  <h3 class="text-center">詳細</h3>

  <div class="card mb-3">
    <%= image_tag @imgpost.image_url, width: "50%", height: "50%" if @imgpost.image? %>
    <div class="card-body">
      <h5 class="card-title"><%= @imgpost.title %></h5>
      <p class="card-text"><%= @imgpost.body %></p>
      <p class="card-text"><small class="text-muted"><%= @imgpost.created_at %></small></p>
      <p class="card-text">
        <% if user_signed_in? %>
          <% if current_user.already_liked?(@imgpost) %>
              <%= link_to imgpost_like_path(@imgpost), method: :delete do %>
                  <i class="fas fa-heart"></i><%= @imgpost.likes.count %>
              <% end %>
          <% else %>
              <%= link_to imgpost_likes_path(@imgpost), method: :post do %>
                  <i class="far fa-heart"></i><%= @imgpost.likes.count %>
              <% end %>
          <% end %>
        <% else %>
          <i class="far fa-heart"></i><%= @imgpost.likes.count %>
        <% end %>
      </p>
      <p class="card-text">いいねしたユーザー</p>
      <p class="card-text">
        <% @imgpost.liked_users.each do |user| %>
          <li><%= user.email %></li>
        <% end %>
      </p>
      <p class="card-text">コメント一覧</p>
      <p class="card-text">
        <% @comments.each do |c| %>
          <div>
            <%= c.user.email unless c.user.blank? %>
            <br>
            <%= c.content %>
          </div>
          <p><%=link_to "削除", comment_path(c.id), class: "btn btn-dark" , method: :delete %></p>
          <br>
        <% end %> 
        <% if user_signed_in? %>
          <%= form_with(model: [@imgpost, @comment], local: true) do |f| %>
            <%= f.text_area :content , class: 'form-control' %>
            <%= button_tag type: "submit" , class: 'btn btn-primary mt-3' do %>
              <i class="far fa-comments"></i> コメントする
            <% end %>
          <% end %>
        <% end %>    
      </p>
      <p class="card-text">
        <%= link_to "編集する", edit_imgpost_path(@imgpost.id) , class: 'btn btn-primary' %>
      </p>
      <p class="card-text">
        <%= link_to "トップへ戻る", imgposts_path , class: "btn btn-secondary" %>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeekInstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%# フッター部分 %>
    <footer class="footer">
      <small>© kidayuki. 2021.</small>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローを解除する', class: 'btn btn-danger' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'フォローする', class: 'btn btn-primary' %>
    <% end %>
  <% end %>
<% end %>

app/views/top/index.html.erb
<div class="top-section">
  <div class="top-inner">
    <div class="top-title">
      <p class="top-title-icon"><i class="fas fa-door-open"></i></p>
      <h1 class="top-title-text">GeekInstagramへようこそ</h1>
    </div>
    <div class="top-item">
      <%= link_to "ログイン", imgposts_path , class: 'login-btn' %>
    </div>
    <div class="top-item">
      <p>or</p>
    </div>
    <div class="top-item">
      <%= link_to "新規登録", new_user_registration_path , class: 'signup-btn' %>
    </div>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <div class="login-link">
    <%= link_to "ログイン", new_session_path(resource_name) , class: 'link-text' %><br />
  </div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <div class="inline-block">
    <%= link_to "アカウント作成", new_registration_path(resource_name) , class: 'link-text' %><br />
  </div>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <div class="inline-block">
    <%= link_to "パスワードをお忘れですか?", new_password_path(resource_name) , class: 'link-text' %><br />
  </div>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="text-center">
  <h1 class="mypage-title">マイページ</h1>
  <div class="profile">
    <%= image_tag @user.image_url ,  class: 'mypage-image' if @user.image? %>
    <p>名前 : <%= @user.name %></p>
    <p>メールアドレス : <%= @user.email %></p>
    <p>プロフィール : <%= @user.profile %></p>
  </div>

  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path , class: 'btn btn-primary' %>
  <% end %>

  <div class="follow">
    <%= render 'relationships/follow_button', user: @user %>
  </div>

  <h2 class="mypage-title">ユーザーの投稿一覧</h2>
  <% @user.imgposts.each do |t| %>
    <div class="py-3">
      <p class="font-weight-bold"><%= t.title %></p>
      <%= t.body %>
    </div>
  <% end %>

  <br>
  <p><%= link_to "一覧に戻る", imgposts_path , class: 'btn btn-link' %></p>
</div>